apiVersion: v1
kind: Namespace
metadata:
  name: bench
  labels:
   istio-injection: enabled


---
apiVersion: v1
kind: Service
metadata:
  name: ctrl
  namespace: bench
spec:
  selector:
    app: ctrl
  ports:
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl
  namespace: bench
spec:
  selector:
    matchLabels:
      app: ctrl
  replicas: 1
  template:
    metadata:
      labels:
        app: ctrl
    spec:
      containers:
      - name: ctrl
        imagePullPolicy: IfNotPresent
        image: a.com/benchmark:1
        command: ["/cperf"]
        args: ["ctrl"]
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sink
  namespace: bench
spec:
  selector:
    app: sink
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
  namespace: bench
spec:
  selector:
    matchLabels:
      app: sink
  replicas: 2
  template:
    metadata:
      labels:
        app: sink
    spec:
      containers:
      - name: sink
        imagePullPolicy: IfNotPresent
        image: a.com/benchmark:1
        command: ["/cperf"]
        args: ["sink"]
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  namespace: bench
spec:
  selector:
    matchLabels:
      app: cli
  replicas: 2
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
      - name: cli
        imagePullPolicy: IfNotPresent
        image: a.com/benchmark:1
        command: ["/cperf"]
        args: ["client"]

